linters:

  IdSelector:
    enabled: false

  SelectorDepth:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: false

  ImportantRule:
    enabled: false

  VendorPrefix:
    enabled: false

  PseudoElement:
    enabled: false

  NestingDepth:
    enabled: false